services:
  nginx:
    image: nginx:alpine
    container_name: grippo_nginx_local
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.local.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - backend
    restart: unless-stopped