services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${POSTGRES_DATABASE}
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./dump.sql:/docker-entrypoint-initdb.d/dump.sql
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    container_name: "${POSTGRES_CONTAINER_NAME}"